routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['siteDisable']], function () {

    Route::get('api/auth', 'TestController@auth');

    Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
    Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

    Route::get('/', 'HomeController@index');
    Route::get('cabinet', 'CabinetController@index');
    Route::get('cabinet/profile', 'CabinetController@history');
    Route::get('cabinet/contacts', 'CabinetController@contacts');
    Route::get('cabinet/settings', 'CabinetController@settings');

    Route::get('user/get', 'Api\CabinetController@user');
    Route::post('user/update', 'Api\CabinetController@update');

    Route::post('user/avatar/upload', 'Api\CabinetController@uploadAvatar');
    Route::post('user/{id}/avatar/delete', 'Api\CabinetController@deleteAvatar');

    Route::post('/new/order', 'OrderController@newOrder');
    Route::post('repeat/order/{id}', 'OrderController@repeatOrder');
    Route::post('/product/{id}/add', 'OrderController@addSingle');

    Route::get('order/{id}/accepted', ['as' => 'orderaccepted', 'uses' => 'OrderController@accepted']);

    /* payment */

    Route::get('confirmation', ['as' => 'orderconfirm', 'uses' => 'OrderController@confirmation']);
    Route::post('kkb/postlink', 'OrderController@postlink');

    Route::get('cart', 'CartController@index');
    Route::get('delivery', 'PageController@delivery');
    Route::get('checkout', 'PageController@checkout');

    Route::get('about', 'PageController@about');
    Route::get('contacts', 'PageController@contacts');
    Route::get('test', 'PageController@test');

    Route::get('product/single', 'CatalogController@single');
    Route::get('registration', 'UserController@registration');
    Route::get('password/reset', 'UserController@resetPass');

    Route::get('catalog/{slug}', ['as' => 'catalogIndex', 'uses' => 'CatalogController@index']);
    Route::get('catalog/{category_slug}/{slug}', 'CatalogController@single');

    Route::get('/type/product/get', 'Api\CatalogController@getProductByType');

    Route::post('user/auth', 'Auth\LoginController@login');
    Route::get('user/logout', 'Auth\LoginController@logout');

    Route::get('products/category/{id}/get', 'Api\CatalogController@getProducts');
    Route::get('popular/products/get', 'HomeController@popularProducts');


    Route::get('product/{id}/reviews/get', 'Api\ReviewController@getReviews');
    Route::post('product/{id}/review/save', 'Api\ReviewController@save');
    Route::get('recent/reviews/get', 'Api\ReviewController@recent');

    Route::get('slider/products/get', 'Api\CatalogController@slider');
    Route::get('product/{id}/recommend/get', 'Api\CatalogController@recommend');

    Route::get('get/nomenclature/{city}', 'Api\CatalogController@getNomenclature');
    Route::post('get/order', 'Api\CatalogController@getOrderInfo');
    Route::post('create/order', 'Api\CatalogController@createOrder');

    Route::get('{object_type}/{id}/images/get', 'ImageController@getImages');
    Route::get('{object_type}/{id}/image/get', 'ImageController@getImage');
    Route::post('{object_type}/{object_id}/image/upload', 'ImageController@upload');
    Route::post('{object_type}/{object_id}/image/{image_id}/delete', 'ImageController@deleteGalleryImg');

    Route::post('user/create', 'OrderController@createUser');
    Route::post('change/city', 'CityController@change');


    Route::get('apply-promocode', 'PromocodeController@getPromocode');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::get('integration', 'Admin\IntegrationController@index');
    Route::get('products-almaty', 'Admin\ProductController@index');
    Route::get('products-astana', 'Admin\ProductController@index');
    Route::get('shop-2', 'Admin\ProductController@shop_2');

});

Auth::routes();

Route::post('/language', array(
    'Middleware' => 'Locale',
    'uses' => 'LanguageController@index'
));

app/Review.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    //

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getRatingStarsAttribute()
    {
        for ($x = 1; $x <= $this->rating; $x++) {
            echo '<i class="rating_star "></i>';
        }
        if (strpos($this->rating, '.')) {
            echo '<i class="rating_star_empty"></i>';
            $x++;
        }
        while ($x <= 5) {
            echo '<i class="rating_star_empty"></i>';
            $x++;
        }
    }
}

app/Http/Controllers/Api/CatalogController.php
<?php

namespace App\Http\Controllers\Api;

use App\Category;
use App\City;
use App\Helpers;
use App\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Input;

class CatalogController extends Controller
{
    //
    const URL = 'https://iiko.biz:9900/api/0';

    public function getToken($city)
    {
        $token = curl_get(self::URL . '/auth/access_token', array('user_id' => $city->login, 'user_secret' => $city->pass ));
        return trim($token, '"');
    }

    public function getOrganizationList($city)
    {
        $organizations = curl_get(self::URL . '/organization/list', array('access_token' => $this->getToken($city)));
        return $organizations;
    }

    public function getNomenclature($citySlug)
    {

        $city = City::where('slug', $citySlug)->first();
        $organization = array_first(\GuzzleHttp\json_decode($this->getOrganizationList($city)));
        $categories_json = curl_get(self::URL . '/nomenclature/' . $organization->id, array('access_token' => $this->getToken($city)));
        $categories = \GuzzleHttp\json_decode($categories_json)->groups;
        $products = \GuzzleHttp\json_decode($categories_json)->products;

        $this->categoriesSave($categories, $city->slug);
        $this->productsSave($products, $city->slug);

        return response()->json();
    }

    public function getOrderInfo($city)
    {
        $order_id = '52966';
        $organization_id = 'c1b3fbe3-5fd6-11e7-80df-d8d38565926f';
        return curl_get(self::URL . '/orders/info', array(CURLOPT_HTTPHEADER => array('Content-Type: application/json; charset=utf-8'), 'access_token' => $this->getToken($city), 'organization' => $organization_id, 'order' => $order_id));
    }


    public function categoriesSave($categories, $city)
    {
        foreach ($categories as $category) {

            if (Category::where('iiko_id', '=', $category->id)->exists()) {
                $old_cat = Category::where('iiko_id' , $category->id)->first();
                $old_cat->name = $category->name;
                $old_cat->slug = Helpers::str2url( $old_cat->name);
                $old_cat->order = $category->order;
                $old_cat->city = $city;
                $old_cat->save();
            }
            
            else {
                $new_cat = new Category();
                $new_cat->name = $category->name;
                $new_cat->slug = Helpers::str2url($new_cat->name);
                $new_cat->iiko_id = $category->id;
                $new_cat->order = $category->order;
                $new_cat->city = $city;
                $new_cat->save();
            }
        }
    }

    public function productsSave($products , $city)
    {
        foreach ($products as $product) {

            if (Product::where('iiko_id', '=', $product->id)->exists()) {
                $old_product = Product::where('iiko_id' , $product->id)->first();
                $old_product->title = $product->name;
                $old_product->slug = Helpers::str2url( $old_product->title);
                $old_product->price = $product->price;
                $old_product->category_id = $product->parentGroup;
                $old_product->type = $product->type;
                $old_product->city = $city;
                $old_product->order = $product->order;
                $old_product->save();
            }

            else {
                $new_product = new Product();
                $new_product->title = $product->name;
                $new_product->slug = Helpers::str2url($new_product->title);
                $new_product->iiko_id = $product->id;
                $new_product->price = $product->price;
                $new_product->category_id = $product->parentGroup;
                $new_product->type = $product->type;
                $new_product->city = $city;
                $new_product->order = $product->order;
                $new_product->save();
            }
        }
    }

    public function getProducts($id)
    {

        $category = Category::find($id);

        $products = $category->products()->where('city' ,City::getCookieCity())->where('active' , 1)->with('category')->get();
      
        return response()->json($products);
    }

    public function slider(Request $request)
    {
        $products = Product::where('in_slider', 1)->where('active', 1)->get();

        $arr = [];

        foreach ($products as $key => $product) {
            $item = [];
            $item['id'] = $product->id;
            $item['iiko_id'] = $product->iiko_id;
            $item['title'] = $product->title;
            $item['price'] = $product->price;
            $item['image'] = $product->image;
            $item['weight'] = $product->weight;
            $arr[$product->id] = $item;
        }

        return response()->json($arr);
    }

    public function recommend($id)
    {
        $product = Product::find($id);

        $arr = [];
        foreach ($product->recommend as $key => $product) {

            $item = [];
            $item['id'] = $product->id;
            $item['iiko_id'] = $product->iiko_id;
            $item['title'] = $product->title;
            $item['price'] = $product->price;
            $item['image'] = $product->image;
            $item['weight'] = $product->weight;
            $arr[$product->id] = $item;
        }
        return response()->json($arr);
    }

    public function getProductByType(Request $request)
    {
        $product = [];

        if ($request->type == 'simple')
        {
            $product = Product::with('category')->get();
            return response()->json($product);
        }

//        if ($request->type == 'top-left')
//        {
//            $product = Product::where('type' , 'top-left')->with('category')->first();
//            return response()->json($product);
//        }
//
//        if ($request->type == 'top-right')
//        {
//            $product = Product::where('type' , 'top-right')->with('category')->first();
//            return response()->json($product);
//        }
//
//        if ($request->type == 'right-bottom')
//        {
//            $product = Product::where('type' , 'right-bottom')->with('category')->first();
//            return response()->json($product);
//        }
//
        return response()->json($product);
    }


}

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\City;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;

class CatalogController extends Controller
{

    public function index($slug)
    {
        $category = Category::where('slug', $slug)->where('city', City::getCookieCity())->where('active', 1)->first();

        

        return view('catalog.index', compact('category', 'products'));
    }

    public function single($category_slug, $slug)
    {
        $product = Product::where('slug' , $slug)->where('city' , City::getCookieCity())->first();
        
        if (!$product)
        {
            return redirect('/');
        }
        return view('catalog.single', compact('product'));
    }
    
}

resources/views/catalog/index.blade.php
@extends('layouts.page')
@section('content')

    
    <div class="category-page" ng-controller="CatalogController as cg">
        <div class="container">
            <div class="row no-padding">

                <div class="clearfix"></div>
                <div class="title-wrap">
                    <div class="col-lg-12">
                        <div class="title title-category"> {{ $category->name }} </div>
                    </div>
                    <div class="title-mobile">
                        <div class="col-lg-12">
                            <div class="title"> Меню: <span> {{ $category->name }} </span></div>
                        </div>
                    </div>
                </div>

                @if($category->slug == 'sety')
                    <div class="alert alert-info" style="font-size: 16px;">
                        Акция на сеты не действует в выходные и праздничные дни.
                    </div>
                @endif

                <div class="content">
                    <div class="products-list-index" ng-init="cg.products('{{$category->id}}')">
                        <div class="product simple col-lg-12" ng-repeat="product in cg.categoryProducts">
                            <div class="top">
                                <a href="/catalog/@{{ product.category.slug }}/@{{ product.slug }}">
                                    <div class="image">
                                        <img src="@{{ product.main_image }}" alt="">
                                    </div>
                                    <div class="title"><span ng-bind="product.title"></span></div>
                                </a>
                            </div>
                            <div class="clearfix"></div>
                            <div class="description">

                                <div class="text" ng-bind="product.text"></div>
                                <div class="footer row">

                                    <div class="col-lg-6 col-xs-6">
                                        <div class="price"> @{{ product.price }} ₸</div>
                                        <div class="count">
                                            <span>1 порция </span>
                                            <span> @{{ product.weight }}</span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-xs-6">
                                        <div class="add-to-cart"
                                             ng-class="{flip: ct.cart[product.id].quantity == 0 || ct.cart[product.id].quantity != undefined}">
                                            <div class="btn-wrap front">
                                                <a href="#" class="btn btn-orange"
                                                   ng-click="ct.addToCart(product);$event.preventDefault()">
                                                    Заказать
                                                </a>
                                            </div>
                                            <div class="quantity-control back">
                                                <ul>
                                                    <li class="control-btn minus" ng-click="ct.minus(product)"></li>
                                                    <li class="control-qty">@{{ ct.cart[product.id].quantity || 0}}</li>
                                                    <li class="control-btn plus"
                                                        ng-click="ct.addToCart(product);$event.preventDefault()"></li>
                                                </ul>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/catalog/single.blade.php
@extends('layouts.page')

@section('content')

    <div class="clearfix"></div>
    <div class="product-single" ng-controller="CatalogController as cg">
        <div class="container">

            <div class="row no-padding">
                <div class="col-lg-12 hidden-xs">
                    <div class="breadcrumbs">
                        <ul>
                            <li><a href="/"> @lang('product.rumi_name') </a></li>
                            <li><a href="/catalog/{{ $product->category->slug }}">{{ $product->category->name }}</a></li>
                            <li>{{ $product->title }}</li>
                        </ul>
                    </div>
                </div>
                <div class="clearfix"></div>

                <div class="col-lg-7">
                    <div class="slider">
                        <section class="slider-product" >

                            @foreach($product->images()->where('object_id' , $product->id)->get() as $image)
                                <div data-thumb="{{$image->url}}"><img src="{{$image->url}}"></div>
                            @endforeach
                        </section>

                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="right-block">
                        <div class="product">
                            <div class="title">{{ $product->title }}</div>
                            <div class="review-block">
                                <span class="rating-star-wrap">{{ $product->rating_stars }}</span>
                                <div class="review-count"><a href="#reviews">{{ $product->reviews()->count() }} {{ \App\Helpers::review_str($product->reviews()->count()) }}</a></div>

                            </div>
                            <div class="text">
                                {{ $product->text }}
                            </div>

                            <div class="text composition">
                                <span>Состав:</span>
                                {{ $product->composition }}
                            </div>

                           <div class="footer">
                               <div class="col-lg-6 col-xs-6">
                                   <div class="price"> {{ $product->price }} ₸</div>
                                   <div class="count">
                                       <span> 1 порция </span>
                                       <span> {{ $product->weight }}</span>
                                   </div>
                               </div>
                               <div class="col-lg-6 col-xs-6">
                                   <div class="add-to-cart" ng-class="{flip: ct.cart[ct.singleProduct.id].quantity == 0 || ct.cart[ct.singleProduct.id].quantity != undefined}">
                                       <div class="btn-wrap front" >
                                           <a href="#" class="btn btn-orange" ng-click="ct.addToCart(ct.singleProduct);$event.preventDefault()">
                                               Заказать
                                           </a>
                                       </div>
                                       <div class="quantity-control back" ng-init="ct.addSingleProduct('{{$product->id}}')">
                                           <ul>
                                               <li class="control-btn minus" ng-click="ct.minus(ct.singleProduct)"></li>
                                               <li class="control-qty" ng-bind="ct.cart[ct.singleProduct.id].quantity || 0"></li>
                                               <li class="control-btn plus" ng-click="ct.addToCart(ct.singleProduct);$event.preventDefault()"></li>
                                           </ul>
                                       </div>
                                   </div>
                               </div>
                           </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="recommended">
            <div class="container">
                <div class="row no-padding">
                    <div class="col-lg-12">
                        <div class="title-wrap">
                            {{--<div class="title">К "{{$product->title}}", мы рекомендуем:</div>--}}

                            <div class="title">@lang('product.recommend_title' , ['product'=> $product->title]):</div>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="products-list-index">
                        <div class="recommendslider" ng-init="cg.recommendedProducts('{{$product->id}}')">
                            @foreach($product->recommend as $product)
                                <div class="item product">
                                    <a href="/catalog/{{$product->category->slug}}/{{$product->slug}}">
                                        <div class="image"><img src="{{ $product->main_image }}" alt=""></div>
                                        <div class="title"><span>{{ $product->title }}</span></div>
                                    </a>
                                    <div class="description">
                                        <div class="footer">
                                            <div class="">
                                                <div class="col-lg-6 col-xs-6">
                                                    <div class="price"> {{ $product->price }} ₸</div>
                                                    <div class="count">
                                                        <span>1 порция </span>
                                                        <span>450 гр.</span>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-xs-6">

                                                    <div class="add-to-cart" ng-class="{flip: ct.cart['{{$product->id}}'].quantity == 0 || ct.cart['{{$product->id}}'].quantity != undefined}">
                                                        <div class="btn-wrap front">
                                                            <a href="#" class="btn-orange" ng-click="ct.addToCart(cg.recommend['{{$product->id}}']);$event.preventDefault()">
                                                                Заказать
                                                            </a>
                                                        </div>

                                                        <div class="quantity-control back">
                                                            <ul>
                                                                <li class="control-btn minus" ng-click="ct.minus(cg.recommend['{{$product->id}}'])"></li>
                                                                <li class="control-qty" ng-bind="ct.cart['{{$product->id}}'].quantity || 0"></li>
                                                                <li class="control-btn plus" ng-click="ct.addToCart(cg.recommend['{{$product->id}}']);$event.preventDefault()"></li>
                                                            </ul>
                                                        </div>

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach

                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div id="reviews" class="reviews-block" ng-controller="ReviewsController as rv" ng-init="rv.getReviews('{{$product->id}}')">
            <div class="container">
                <div class="row no-padding">
                    <div class="col-lg-12">
                        <div class="title-wrap">
                            <div class="title"> @lang('product.user_reviews')</div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-lg-5">
                        <div class="wrap-form">
                            @if (Auth::guest())
                                <div class="authorized">
                                    <div class="title"> @lang('product.enter_reviews')</div>
                                    <div class="caption">
                                        @lang('product.logged')
                                    </div>
                                    <div class="btn-wrap">
                                        <a href="#" class="btn btn-blue"> @lang('product.login_register') </a>
                                    </div>
                                </div>
                            @else
                                <div class="noauthorized">
                                    <form ng-submit="rv.save('{{$product->id}}')">
                                        <div class="title"> @lang('product.enter_reviews')</div>
                                        <div class="text">
                                        <textarea ng-model="rv.textReview" name="text" class="input-std" id="" cols="10"
                                                  rows="3"
                                                  placeholder="Текст отзыва ..." required></textarea>
                                        </div>
                                        <div class="rating">
                                            <span>Ваша оценка: </span>
                                            <fieldset>
                                            <span class="star-cb-group stars-wrap">
                                                <i ng-repeat="n in [].constructor(5) track by $index"
                                                   ng-click="rv.rating = $index + 1;"
                                                   ng-class="($index + 1) <= rv.rating ?  'rating_star' : 'rating_star_empty'"
                                                   class="rating-star"></i>
                                             </span>
                                            </fieldset>
                                        </div>
                                        <div class="btn-wrap">
                                            <input type="submit" class="btn btn-blue" value="Опубликовать">
                                        </div>
                                    </form>
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="col-lg-6 col-lg-offset-1">
                        <div class="reviews-list">

                            <div class="review" ng-repeat="review in rv.reviews">
                                <div class="col-lg-6">
                                    <div class="user-info">
                                        <div class="user-image">
                                            <img src="/@{{ review.user.avatar }}" alt=""></div>
                                        <div class="user-name">
                                            <div class="star">
                                                 <span class="rating-star-wrap">
                                                    <i ng-repeat="n in [].constructor(5) track by $index"
                                                       ng-class="($index + 1) <= review.rating ? 'rating_star' : 'rating_star_empty'"></i>
                                                </span>
                                            </div>
                                            <div class="name">@{{ review.user.name }}</div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="date">
                                        @{{ review.date }}
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                                <div class="text">
                                    @{{ review.text }}
                                </div>
                            </div>

                            <div class="review" ng-if="rv.reviews.length == 0">
                                <h4> @lang('product.first_reviews')</h4>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection