routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => ['siteDisable']], function () {

    Route::get('api/auth', 'TestController@auth');

    Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
    Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

    Route::get('/', 'HomeController@index');
    Route::get('cabinet', 'CabinetController@index');
    Route::get('cabinet/profile', 'CabinetController@history');
    Route::get('cabinet/contacts', 'CabinetController@contacts');
    Route::get('cabinet/settings', 'CabinetController@settings');

    Route::get('user/get', 'Api\CabinetController@user');
    Route::post('user/update', 'Api\CabinetController@update');

    Route::post('user/avatar/upload', 'Api\CabinetController@uploadAvatar');
    Route::post('user/{id}/avatar/delete', 'Api\CabinetController@deleteAvatar');

    Route::post('/new/order', 'OrderController@newOrder');
    Route::post('repeat/order/{id}', 'OrderController@repeatOrder');
    Route::post('/product/{id}/add', 'OrderController@addSingle');

    Route::get('order/{id}/accepted', ['as' => 'orderaccepted', 'uses' => 'OrderController@accepted']);

    /* payment */

    Route::get('confirmation', ['as' => 'orderconfirm', 'uses' => 'OrderController@confirmation']);
    Route::post('kkb/postlink', 'OrderController@postlink');

    Route::get('cart', 'CartController@index');
    Route::get('delivery', 'PageController@delivery');
    Route::get('checkout', 'PageController@checkout');

    Route::get('about', 'PageController@about');
    Route::get('contacts', 'PageController@contacts');
    Route::get('test', 'PageController@test');

    Route::get('product/single', 'CatalogController@single');
    Route::get('registration', 'UserController@registration');
    Route::get('password/reset', 'UserController@resetPass');

    Route::get('catalog/{slug}', ['as' => 'catalogIndex', 'uses' => 'CatalogController@index']);
    Route::get('catalog/{category_slug}/{slug}', 'CatalogController@single');

    Route::get('/type/product/get', 'Api\CatalogController@getProductByType');

    Route::post('user/auth', 'Auth\LoginController@login');
    Route::get('user/logout', 'Auth\LoginController@logout');

    Route::get('products/category/{id}/get', 'Api\CatalogController@getProducts');
    Route::get('popular/products/get', 'HomeController@popularProducts');


    Route::get('product/{id}/reviews/get', 'Api\ReviewController@getReviews');
    Route::post('product/{id}/review/save', 'Api\ReviewController@save');
    Route::get('recent/reviews/get', 'Api\ReviewController@recent');

    Route::get('slider/products/get', 'Api\CatalogController@slider');
    Route::get('product/{id}/recommend/get', 'Api\CatalogController@recommend');

    Route::get('get/nomenclature/{city}', 'Api\CatalogController@getNomenclature');
    Route::post('get/order', 'Api\CatalogController@getOrderInfo');
    Route::post('create/order', 'Api\CatalogController@createOrder');

    Route::get('{object_type}/{id}/images/get', 'ImageController@getImages');
    Route::get('{object_type}/{id}/image/get', 'ImageController@getImage');
    Route::post('{object_type}/{object_id}/image/upload', 'ImageController@upload');
    Route::post('{object_type}/{object_id}/image/{image_id}/delete', 'ImageController@deleteGalleryImg');

    Route::post('user/create', 'OrderController@createUser');
    Route::post('change/city', 'CityController@change');


    Route::get('apply-promocode', 'PromocodeController@getPromocode');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();

    Route::get('integration', 'Admin\IntegrationController@index');
    Route::get('products-almaty', 'Admin\ProductController@index');
    Route::get('products-astana', 'Admin\ProductController@index');
    Route::get('shop-2', 'Admin\ProductController@shop_2');

});

Auth::routes();

Route::post('/language', array(
    'Middleware' => 'Locale',
    'uses' => 'LanguageController@index'
));

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function reviews()
    {
        return $this->hasMany(Review::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    function socialProviders()
    {
        return $this->hasMany(SocialProvider::class);
    }

    function getDateRegisterAttribute()
    {
        $date = new Carbon($this->created_at);
        return $date->format('j') .' '. trans('months.'.$date->format('F').''). ', ' . $date->format('Y').' г.';
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/cabinet.blade.php
@include('layouts.header')

<div class="page">

    <div class="cabinet-page" ng-controller="CabinetController as cb">
        <div class="container">
            <div class="row no-padding">
                <div class="title-page"> @lang('cabinet.title')</div>
                <div class="clearfix"></div>
                <div class="col-lg-4">

                    <div class="user-block">
                        <div class="col-lg-2 col-xs-12">
                            <div class="image"><img src="/@{{ cb.user.avatar }}" alt=""></div>
                        </div>
                        <div class="col-lg-10 col-xs-12">
                            <div class="info">
                                <div class="name"> @{{ cb.user.name }} </div>
                                <div class="age"> @{{ cb.currentYear - cb.user.born }} года, @{{ genderUser.name }}</div>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="more-info">
                            <div class="field">
                                <div class="col-lg-6 col-xs-6">
                                    <div class="name"> @lang('cabinet.date_of_registration') </div>
                                </div>
                                <div class="col-lg-6 col-xs-6">
                                    <div class="value"> {{ $user->date_register }}</div>
                                </div>
                            </div>

                            <div class="field">
                                <div class="col-lg-6 col-xs-6">
                                    <div class="name"> @lang('cabinet.posted_reviews') </div>
                                </div>
                                <div class="col-lg-6 col-xs-6">
                                    <div class="value"> {{ $user->reviews->count() }} @lang('cabinet.reviews')</div>
                                </div>
                            </div>
                            <div class="field">
                                <div class="col-lg-6 col-xs-6">
                                    <div class="name"> @lang('cabinet.my_orders') </div>
                                </div>
                                <div class="col-lg-6 col-xs-6">
                                    <div class="value"> {{ $user->orders->count() }} покупки</div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-8">
                    <div class="right-block">
                        <div class="menu-cabinet">
                            <ul>
                                <li class="{{ Request::is('cabinet/profile') ? 'active' : '' }}"><a href="/cabinet/profile"> @lang('cabinet.history_of_orders') </a></li>
                                <li class="{{ Request::is('cabinet/contacts') ? 'active' : '' }}"><a href="/cabinet/contacts"> @lang('cabinet.address_and_phone') </a></li>
                                <li class="{{ Request::is('cabinet/settings') ? 'active' : '' }}"><a href="/cabinet/settings"> @lang('cabinet.settings_of_profile')  </a></li>
                            </ul>
                        </div>
                        <div class="content">
                            @yield('cabinet')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@include('layouts.footer')

resources/views/layouts/main-menu.blade.php
<ul>
    @foreach(\App\Category::where('city', \App\City::getCookieCity())->where('active', 1)->orderBy('order', 'asc')->get() as $category)
        <li class="{{ Request::is('catalog/'. $category->slug) ? 'active' : '' }}">
            <a href="/catalog/{{ $category->slug }}">
                <div class="icon">
                    <img src="{{ Voyager::image($category->image) }}" class="svg" alt="">
                </div>
                <div class="name"> {{ $category->name }}</div>
            </a>
        </li>
    @endforeach
</ul>

resources/views/layouts/page.blade.php
@include('layouts.header')

<div class="page">
    @yield('content')
</div>

@include('layouts.footer')

resources/views/layouts/select-city.blade.php
<form action="/change/city" method="post">
    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <select name="city" onchange="this.form.submit(); ct.clearSession()">
        <option value="almaty" @if( Cookie::get('city') == 'almaty' ) selected @endif> @lang('main.almaty') </option>
        <option value="astana" @if( Cookie::get('city') == 'astana' ) selected @endif> @lang('main.astana') </option>
    </select>
</form>

resources/views/layouts/select-lang.blade.php
<form action="/language" method="post">

    <input type="hidden" name="_token" value="{{ csrf_token() }}">
    <select name="locale" onchange="this.form.submit()">
        <option value="ru" @if(App::getLocale() == 'ru') selected @endif > Русский </option>
        <option value="kz" @if(App::getLocale() == 'kz') selected @endif > Қазақша </option>
        <option value="en" @if(App::getLocale() == 'en') selected @endif > English</option>
    </select>

</form>